twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public': public_path

    globals:
        # the value is the service's id
        menuService: '@App\Menu\MenuService'
